name: Wyckoff Scanner
on:
  schedule:
    - cron: '0 9 * * *'  # 10:00 Italia
    - cron: '0 12 * * *' # 13:00 Italia
    - cron: '0 15 * * *' # 16:00 Italia
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: {python-version: '3.9'}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Esecuzione
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
